import { Serie } from './serie';

export const SERIES: Serie[] = [
  { idSERIE: 11, titre: 'Eleventh Hour', description:"Un scientifique du gouvernement et son attrayant responsable du FBI tentent de pr�server les populations d\'exp�riences scientifiques mortelles, d\'empoisonneurs, de maladies rares et de risques environnementaux." , annee:"2008-2009" , image:"https://m.media-amazon.com/images/M/MV5BMTY3OTEzODA1OV5BMl5BanBnXkFtZTcwODQwOTIxMw@@._V1_SX300.jpg" },
  { idSERIE: 12, titre: 'Fear Itself', description:"Une s�rie t�l�vis�e divis�e en treize films de soixante minutes d\'�crivains et de r�alisateurs d\'horreur." , annee:"2008-2009" , image:"https://m.media-amazon.com/images/M/MV5BMTY4NzE5NjU1OF5BMl5BanBnXkFtZTcwMzU5MDEwNQ@@._V1_SX300.jpg" },
  { idSERIE: 13, titre: 'Flight of the Conchords', description: 'Bret et Jemaine sont Flight of the Conchords, un groupe de folk-rock n�o-z�landais install� � New York � la recherche de la c�l�brit�.', annee: '2007�2009', image:'https://m.media-amazon.com/images/M/MV5BMTg0NzQ3NzE2MV5BMl5BanBnXkFtZTcwODkxMjY1Mw@@._V1._CR42,18,329,459_SY132_CR3,0,89,132_AL_.jpg_V1_SX300.jpg'},
  { idSERIE: 14, titre: 'Friday Night Lights', description:'Les �preuves et les tribulations des footballeurs texans de petites villes, de leurs amis, de leur famille et de leurs entra�neurs.', annee:'2006�2011', image:'https://m.media-amazon.com/images/M/MV5BMTYwNjIyMTYwOV5BMl5BanBnXkFtZTcwMTA2MDU1MQ@@._V1_SX300.jpg'},
  { idSERIE: 15, titre: 'Gary Unmarried', description:'Nouvellement divorc� apr�s quinze ans de mariage, Gary Brooks, un entrepreneur en peinture, s\'efforce de concilier travail, garde partag�e de ses deux enfants, une ex-femme dominante et sa nouvelle petite amie fox.', annee:'2008�2010', image:'https://m.media-amazon.com/images/M/MV5BMTczNDY4NjYxNl5BMl5BanBnXkFtZTcwODI2OTY4MQ@@._V1_SX300.jpg'},
  { idSERIE: 16, titre: 'Ghost Whisperer', description:'Une jeune mari�e ayant la capacit� de communiquer avec les esprits des morts surmonte le scepticisme et le doute pour les aider � envoyer leurs messages importants aux vivants et permettre aux morts de passer de l\'autre c�t�.', annee:'2005�2010', image:'https://m.media-amazon.com/images/M/MV5BMTUzODQ0Nzg3OV5BMl5BanBnXkFtZTYwNDI0NDg2._V1_SX300.jpg'},
  { idSERIE: 17, titre: 'Gossip Girl', description:'Les adolescents privil�gi�s vivant dans l\'Upper East Side de New York sont tous accros au blog de Gossip Girl une myst�rieuse blogueuse qui d�voile tous les derniers potins et rumeurs sur leur communaut� tr�s ferm�e', annee:'2007�2012', image:'https://m.media-amazon.com/images/M/MV5BNmQ4Zjg1YWYtMTA1Mi00ZGY1LTlmN2ItYTc5ODkzNTFmYWVhXkEyXkFqcGdeQXVyNjQ0OTk1ODg@._V1_SX300.jpg'},
  { idSERIE: 18, titre: 'Grey\'s Anatomy', description:'Un drame centr� sur la vie personnelle et professionnelle de cinq stagiaires en chirurgie et de leurs superviseurs.',annee: '2005',image: 'https://m.media-amazon.com/images/M/MV5BMTY5OTNjNTctMWYxNC00YjE2LWEzMTMtMTIzMzQ1MzhkODRhXkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_SX300.jpg'},
  { idSERIE: 19, titre: 'How I Met Your Mother', description:'Un p�re raconte � ses enfants, � travers une s�rie de flashbacks, le voyage qu�il a entrepris avec ses quatre meilleurs amis avant de rencontrer sa m�re.',annee: '2005�2014',image: 'https://m.media-amazon.com/images/M/MV5BMTA5MzAzNTcyNjZeQTJeQWpwZ15BbWU3MDUyMzE1MTk@._V1_SX300.jpg'},
  { idSERIE: 20, titre: 'In Treatment', description:'Un psychoth�rapeute s\'interroge sur ses capacit�s et obtient de l\'aide en retrouvant son ancien th�rapeute, qu\'il n\'a pas vu depuis dix ans.',annee: '2008�2010', image:'https://m.media-amazon.com/images/M/MV5BNjM4NzMzMDI1NF5BMl5BanBnXkFtZTcwOTE2MTMwNA@@._V1_SX300.jpg'},
  
];
 
